[package]
org = "ai_samples"
name = "generate_images_using_stabilityai"
version = "0.1.0"
distribution = "2201.4.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "stabilityai"
version = "1.0.0"
repository="local"

